apiVersion: apps/v1
kind: Deployment
metadata:
  name: dual-job-date-api
  namespace: msd21-dual-dating-test
  labels:
    app: dual-job-date-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dual-job-date-api
  template:
    metadata:
      labels:
        app: dual-job-date-api
    spec:
      containers:
        - name: dual-job-date-api
          image: ghcr.io/fh-joanneum-msd/dual-job-date-api:build-develop
          resources:
            limits:
              cpu: 750m
              memory: 750Mi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-credentials