apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dual-job-date-db-claim
  namespace: msd21-dual-dating-test
  labels:
    app: dual-job-date-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi