apiVersion: v1
kind: Service
metadata:
  name: dual-job-date-db
  labels:
    app: dual-job-date-db
    service: dual-job-date-db
spec:
  selector:
    app: dual-job-date-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer