apiVersion: apps/v1
kind: Deployment
metadata:
  name: dual-job-date-web
  namespace: msd21-dual-dating-test
  labels:
    app: dual-job-date
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dual-job-date-web
  template:
    metadata:
      labels:
        app: dual-job-date-web
    spec:
      containers:
        - name: dual-job-date-web
          image: ghcr.io/fh-joanneum-msd/dual-job-date-web:build-develop
          resources:
            limits:
              cpu: 256m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-credentials
