apiVersion: v1
kind: Service
metadata:
  name: dual-job-date-web
  labels:
    app: dual-job-date-web
    service: dual-job-date-web
spec:
  selector:
    app: dual-job-date-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer