apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./frontend/ingress.yaml
  - ./backend/ingress.yaml

images:
  - name: ghcr.io/fh-joanneum-msd/dual-job-date-web
    newTag: build-develop